# docker-compose.yml file
version: '3'

services:
  # Load balancer
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"

  meshtastic-map-1:
    image: kyleg/node-web-app
    container_name: meshtastic-map-1

  meshtastic-map-2:
    image: kyleg/node-web-app
    container_name: meshtastic-map-2

  eclipse-mosquitto:
    image: eclipse-mosquitto:latest
    container_name: eclipse-mosquitto
    restart: unless-stopped
    network_mode: host
    # ports:
    #   - 1883:1883
    #   - 9001:9001
    volumes:
        - ./mosquitto-bridge/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
        - ./mosquitto-bridge/data:/mosquitto/data
        - ./mosquitto-bridge/log:/mosquitto/log
